---
- name: Install NGINX
  ansible.builtin.include_role:
    name: nginxinc.nginx
  vars:
    nginx_branch: stable

- name: Copy configuration files
  ansible.builtin.template:
    src: default.conf.j2
    dest: "/etc/nginx/conf.d/default.conf"
    owner: root
    group: root
    mode: '0644'

- name: Copy application files
  ansible.builtin.template:
    src: index.php.j2
    dest: "/usr/share/nginx/html/index.php"
    owner: nginx
    group: nginx
    mode: '0644'

- name: Reload NGINX
  ansible.builtin.service:
    name: nginx
    state: reloaded
    enabled: true
  changed_when: false
